# Generated by Django 5.1.4 on 2024-12-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('slogan', models.CharField(max_length=200)),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('feature1', models.CharField(max_length=50)),
                ('feature1_image', models.ImageField(upload_to='feature_images/')),
                ('feature2', models.CharField(max_length=50)),
                ('feature2_image', models.ImageField(upload_to='feature_images/')),
                ('feature3', models.CharField(max_length=50)),
                ('feature3_image', models.ImageField(upload_to='feature_images/')),
                ('facilities', models.TextField()),
                ('realtor_name', models.CharField(max_length=100)),
                ('realtor_role', models.CharField(max_length=50)),
                ('realtor_image', models.ImageField(upload_to='realtor_images/')),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
